name : My first GITHUB action

on : pull request

jobs:
    first-job:
        runs-on : ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
         
        - name: List and Read files
          run: |
              echo "My first Action"
              ls -ltra
              cat README.md