name : My first GITHUB action

on : push

jobs:
    first-job:
        runs-on : ubuntu-latest
        steps:
         
        - name: Welcome Message
          run: echo "My first Action"

        - name: List files
          run: ls

        - name: Read File
          run: cat README.md