name : My first shell Script Run

on : push

jobs:
    job1:
        runs-on : ubuntu-latest
        steps:
            - name : checkout Repo
              uses : actions/checkout@v4
        
            - name : Run shell script
              run : |
                chmod +x navin.sh
                ./navin.sh